name: kratos
description: "Native Flutter geometric optics learning simulation."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  audioplayers: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - resources/localization/
    - resources/localization/zh_CN/
    - assets/build_an_atom/images/
    - assets/images/
    - assets/molecules_and_light/
    - assets/images/full_nuclide_chart.png
    - assets/images/build_a_molecule/
    - assets/sounds/
    - assets/data/
    - assets/data/build_a_molecule/
    - assets/scenarios/
    - assets/scenarios/circuit/
    - assets/scenarios/forces/
    - assets/scenarios/color-vision/
    - assets/scenarios/sound/
    - assets/scenarios/radio-waves/
    - assets/scenarios/wave-interference/
    - assets/scenarios/molarity/
    - assets/chemistry/molarity/
    - assets/chemistry/molarity/sounds/
    - assets/scenarios/my-solar-system/
    - assets/density/
    - assets/density/images/materials/
    - assets/buoyancy/images/
    - assets/cck_ac_virtual_lab/images/
    - assets/energy_skate_park/
    - assets/energy_skate_park/usa/
    - assets/energy_skate_park/scenery_phet/
    - assets/phet/vector_addition/
    - assets/phet/vector_addition/scenery_phet/
    - assets/phet/gravity_force_lab_basics/pullers/
    - assets/phet/gravity_force_lab/sounds/
    - assets/phet/waves_intro/
    - assets/phet/diffusion/
    - assets/gases_intro/
    - assets/energy_forms_and_changes/
    - assets/simulations/capacitor_lab_basics/
    - assets/simulations/pendulum_lab/
    - assets/simulations/bending_light/
    - assets/simulations/projectile_motion/
    - assets/simulations/molecule_polarity/
    - assets/simulations/membrane_transport/images/
    - assets/simulations/molecule_polarity/all_molecules.json
    - assets/states_of_matter/mipmaps/
    - assets/states_of_matter/images/
    - assets/astronomy/gravity_and_orbits/
    - assets/simulations/plinko_probability/images/
    - assets/simulations/plinko_probability/sounds/
    - assets/simulations/charges_and_fields/
    - assets/simulations/rutherford_scattering/
    - assets/simulations/isotopes_and_atomic_mass/images/
    - assets/simulations/reactants_products_and_leftovers/images/
    - assets/simulations/faradays_law/
    - assets/simulations/wave_on_a_string/
    - assets/simulations/color_vision/images/
    - assets/simulations/ph_scale/images/
    - assets/simulations/ph_scale/icons/
    - assets/simulations/acid_base_solutions/images/
    - assets/simulations/balancing_act/images/
    - assets/simulations/balancing_act/images/objects/
    - assets/simulations/balancing_act/images/usa/
    - assets/simulations/under_pressure/images/
    - assets/simulations/under_pressure/images/faucet/
    - assets/simulations/friction/sounds/
    - assets/simulations/concentration/images/
    - assets/simulations/concentration/sounds/
    - assets/simulations/john_travoltage/images/
    - assets/simulations/john_travoltage/sounds/
    - assets/simulations/balloons_and_static_electricity/images/
    - assets/simulations/balloons_and_static_electricity/sounds/
    - assets/simulations/forces_and_motion_basics/images/
    - assets/simulations/forces_and_motion_basics/images/pushPullFigures/
    - assets/simulations/forces_and_motion_basics/images/usa/
    - assets/simulations/forces_and_motion_basics/images/africa/
    - assets/simulations/forces_and_motion_basics/images/asia/
    - assets/simulations/forces_and_motion_basics/images/latinAmerica/
    - assets/simulations/forces_and_motion_basics/images/oceania/
    - assets/simulations/forces_and_motion_basics/sounds/
    - assets/simulations/quantum_wave_interference/images/
    - assets/simulations/quantum_wave_interference/sounds/
    - assets/simulations/quantum_coin_toss/images/
    - assets/simulations/quantum_measurement/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
